### ISSUE TITLE
$ python scraper.py执行这一命令报错，求讲解这个仓库的使用方法

### ISSUE THREAD

**Issue by XiaoMe2020** [bonfy/github-trending#13]
![微信截图_20231201210631](https://github.com/bonfy/github-trending/assets/63304323/889f031c-c864-4212-970b-7c1e0cac8c30)

**Comment by XiaoMe2020** [comment]
C:\Users\zzl\github-trending>python scraper.py
python scraper.py
Traceback (most recent call last):
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] ▒▒▒▒▒▒▒ӷ▒▒▒һ▒▒ʱ▒▒▒û▒▒▒▒ȷ▒𸴻▒▒▒▒ӵ▒▒▒▒▒û▒з▒Ӧ▒▒▒▒▒ӳ▒▒▒ʧ▒ܡ▒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zzl\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(

**Comment by bonfy** [comment]
参考 https://github.com/bonfy/github-trending/blob/master/.github/workflows/schedule.yml
